bookmark/urls.py
from django.urls import path, re_path

# 2차 url
from .views import *

# url 이름을 가지고 패턴을 찾고자할 때 namespace를 사용하려면 app_name이 필수!
app_name = 'bookmark'

urlpatterns = [
    # list, write, update, delete
    # 함수형뷰 : 함수이름만
    # 클래스형뷰 : 클래스이름.as_view()

    path('', BookmarkListView.as_view(), name='list'),
    path('write/', BookmarkCreateView.as_view(), name='write'),
    # <1:2> : 1. data type, 2. data name
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
    # re_path(regexp,,),
    # url(regexp,?,?)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# 1차 url
urlpatterns = [
    path('admin/', admin.site.urls),
    # 1차에서 2차인 bookmark urls로 토스
    path('', include('bookmark.urls')),
    #path('bookmark/', include('bookmark.urls')),
    #path('', list, name='index'),
]

bookmark/models.py
from django.db import models

# Create your models here.
# 데이터베이스에 직접 접근하는 것이 아니라 ORM 기능을 통해서 접근
# 모델은 class로 만든다.

class Bookmark(models.Model):
    # 필드 : 데이터베이스에 어떤 컬럼, 어떤 형태, 어떤 제약조건
    # 필드목적2 : 프론트에서 어떤 form tag와 어떤 제약조건을 설정
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    # print 함수를 사용해서 객체를 출력할 때 출력될 내용을 반환하는 함수
    # 장고가 이걸 응용해서 화면에 객체를 html로 출력할 때 내용을 반환하는 함수
    def __str__(self):
        return self.site_name+ " : "+self.url

    class Meta:
        # 해당 모델에 대한 옵션 값
        # 정렬, 출력될 모델 이름
        ordering = ['site_name']

    # Todo : get_absolute_url
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmark:detail', args=[str(self.id)])

bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
# view 두 종류 : 함수형, 클래스형
# 장고 목적? : 귀찮은거 하기 싫어서....
# 클래스형 : 자주 쓰는 기능을 상속받아서 간단하게 생성

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView, DeleteView

# list view
from .models import Bookmark
class BookmarkListView(ListView):
    model = Bookmark
    # 클래스형 뷰는 기본적으로 렌더링할 템플릿 파일이 지정이 되어있습니다.
    # bookmark/bookmark_list.html
    paginate_by = 3

from django.urls import reverse_lazy

class BookmarkCreateView(CreateView):
    model = Bookmark #입력화면에 출력된 form tag를 자동으로 만들어줌
    # _form : create, update
    # default : _form
    template_name_suffix = '_create'
    # 입력받을 필드 목록
    fields = ['site_name','url']
    # get_absolute_url
    success_url =  reverse_lazy('list')


class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

class BookmarkDetailView(DetailView):
    model = Bookmark

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Confirm Delete{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>

{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}Bookmark Write{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Write">
    </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
{{object.site_name}}<br/>
{{object.url}}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}
    Bookmark List
{% endblock %}

{% block content %}
    <div class="btn-group d-block text-right mb-1" role="group">
        <a href="{% url 'bookmark:write' %}" class="btn btn-info">Add Bookmark</a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Site</th>
                <th scope="col">URL</th>
                <th scope="col">Modify</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
                <tr>
                    <td>
                        {{ object.id }}
                    </td>
                    <td>
                        <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.site_name}}</a>
                    </td>
                    <td>
                        {{bookmark.url}}
                    </td>
                    <td><a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                    <td><a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block pagination %}
  {% if is_paginated %}
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'bookmark:list' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}

        {% for object in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}"><a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'bookmark:list' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
  {% endif %}
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}Bookmark Update{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">

          </div>
          <div class="col-4 text-center">
            <a class="header-logo text-dark" href="/">Bookmark</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>

    {% block content %}
    {% endblock %}

    {% block pagination %}
    {% endblock %}
</div>

</body>
</html>